SELECT *  FROM ADMIN.APP_USER  INNER JOIN    ADMIN.USER_ROLE
ON 
ADMIN.USER_ROLE.NAME ='BASIC_USER';
------------------------
INSERT INTO ADMIN.APP_USER (USER_ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, ROLE_ID) 
VALUES
(0, 'DawoudW', '123', 'WAEL', 'DAWOUD', 4);

-------------------------
 SELECT * FROM ADMIN.APP_USER INNER JOIN ADMIN.STUDY_SET 
 ON 
ADMIN.STUDY_SET.OWNER_ID =ADMIN.APP_USER.USER_ID AND ADMIN.APP_USER.USER_ID =4;

-------------------------
 
 SELECT usr.USER_ID,usr.USERNAME,COUNT(std.STUDY_SET_ID) 
	FROM ADMIN.APP_USER usr  INNER JOIN   ADMIN.STUDY_SET std 
	ON usr.USER_ID = STD .OWNER_ID 
	GROUP BY USER_ID,USERNAME
	 