CREATE TABLE TEAM (
TEAM_ID INT PRIMARY KEY AUTO_INCREMENT, -- primary key is a combo constraint of not null a unique
NAME VARCHAR(200) UNIQUE,
MASCOT VARCHAR(200) NOT NULL
);

-- composite key is a PRIMARY key composed of two fields
-- a PRIMARY key uniquely IDENTIfy every record PLAYER_ID or primary key (TEAM_NAME + JERSERY_NUM)

INSERT INTO TEAM VALUES (0,'Globetrotters','Globey the Globe');
INSERT INTO TEAM VALUES (0,'Raptors','Dino');
INSERT INTO TEAM VALUES (0,'Da Bulls','Bull');

CREATE TABLE COACH (
COACH_ID int PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(200) NOT NULL,
SALARY INT,
TEAM_ID int,
CONSTRAINT FK_COACH_TEAM FOREIGN KEY COACH(TEAM_ID) REFERENCES TEAM(TEAM_ID)
);
-- 
-- SELECT * FROM TEAM;
-- SELECT * FROM COACH;

INSERT INTO COACH VALUES (0,'Dylan',1000000,1);
INSERT INTO COACH VALUES (0,'Jaxon',1000000,2);
INSERT INTO COACH VALUES (0,'Alex',1000000,3);
INSERT INTO COACH VALUES (0,'Jackie',1000000,3);
INSERT INTO COACH VALUES (0,'Adam',10000000,1);

CREATE TABLE PLAYER(
PLAYER_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(200)NOT NULL,
JERSEY INT CHECK (JERSEY >= 0 AND JERSEY < 100), -- BETWEEN CONSTRAINT
SALARY INT,
TEAM_ID INT,
CONSTRAINT FK_PLAYER_TEAM FOREIGN KEY PLAYER(TEAM_ID) REFERENCES TEAM(TEAM_ID)
);

INSERT INTO PLAYER VALUES (0,'Dan', 20, 100000,3);
INSERT INTO PLAYER VALUES (0,'Dylan', 10, 100000,3);
INSERT INTO PLAYER VALUES (0,'Ryan', 35, 100000,1);
INSERT INTO PLAYER VALUES (0,'Jamir', 36, 100000,1);
INSERT INTO PLAYER VALUES (0,'Max', 9, 100000,2);
INSERT INTO PLAYER VALUES (0,'Brandon', 12, 100000,2);

SELECT * FROM player;

CREATE TABLE GAME(
GAME_ID INT PRIMARY KEY AUTO_INCREMENT,
LOCATION VARCHAR(200)
);

-- JUNCTION TABLE
CREATE TABLE PLAYER_GAME(
PLAYER_ID INT,
GAME_ID INT,
CONSTRAINT FK_PG_PLAYER FOREIGN KEY PLAYER_GAME(PLAYER_ID) REFERENCES PLAYER(PLAYER_ID),
CONSTRAINT FK_PG_GAME FOREIGN KEY PLAYER_GAME(GAME_ID) REFERENCES GAME(GAME_ID)
);


INSERT INTO GAME VALUES (0,'Morgantown Stadium');
INSERT INTO GAME VALUES (0, 'Madison Square Garden');
INSERT INTO GAME VALUES (0, 'Staple Center');
INSERT INTO GAME VALUES (0, 'Madison Square Garden');

SELECT * FROM PLAYER;
SELECT * FROM GAME;
SELECT * FROM PLAYER_GAME;

INSERT INTO PLAYER_GAME VALUES (1,3); -- DAN ID 1 PLAYED AT THE STAPLE CENTER FOR GAME_ID3
INSERT INTO PLAYER_GAME VALUES (2,3);
INSERT INTO PLAYER_GAME VALUES (6,4);
INSERT INTO PLAYER_GAME VALUES (6,1);
INSERT INTO PLAYER_GAME VALUES (2,4);